config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root "articles#index"

  resources :articles do
    post "drag-update" => "articles#drag_update", as: :drag_update
  end

  resources :major_sections, except: [:index, :show] do
    post "drag-update" => "major_sections#drag_update", as: :drag_update
  end

  resources :minor_sections, except: [:index, :show] do
    post "drag-update" => "minor_sections#drag_update", as: :drag_update
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  validates :title, presence: true
  validates :content, presence: true
  validate :must_belong_to_a_section

  after_create :rank_as_first

  belongs_to :major_section
  belongs_to :minor_section

  scope :ordered, -> { rank(:row_order) }

  def rank_as_first
    self.update_attribute :row_order_position, 0
  end

  private

  def must_belong_to_a_section
    if major_section_id.nil? && minor_section_id.nil?
      errors.add(:base, "Article must belong to a major or a minor section")
    end
  end
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    :url => "/ckeditor_assets/attachments/:id/:filename",
                    :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  s3_credentials_hash = {
    :access_key_id => ENV['AWS_ACCESS_KEY'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  has_attached_file :data,
                    :path => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
                    :s3_credentials => s3_credentials_hash,
                    :bucket => ENV['AWS_BUCKET'],
                    :styles => { :content => '800>', :thumb => '118x100#' },
                    :s3_protocol => :https

  validates_attachment_presence :data
  validates_attachment_size :data, :less_than => 2.megabytes
  validates_attachment_content_type :data, :content_type => /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/major_section.rb
class MajorSection < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  validates :name, presence: true

  after_create :rank_as_first

  has_many :articles, dependent: :destroy
  has_many :minor_sections, dependent: :destroy

  def rank_as_first
    self.update_attribute :row_order_position, 0
  end
end

app/models/minor_section.rb
class MinorSection < ActiveRecord::Base
  include RankedModel
  ranks :row_order

  validates :name, presence: true
  validates :major_section_id, presence: true

  after_create :rank_as_first

  has_many :articles, dependent: :destroy
  belongs_to :major_section

  scope :ordered, -> { rank(:row_order) }

  def rank_as_first
    self.update_attribute :row_order_position, 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @major_sections = MajorSection.rank(:row_order).all
    @articles = Article.rank(:row_order).all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article successfully created!"
      redirect_to article_path(@article)
    else
      flash.now[:alert] = @article.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.assign_attributes(article_params)
    if @article.save
      flash[:notice] = "Article successfully saved!"
      redirect_to article_path(@article)
    else
      flash.now[:alert] = @article.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def drag_update
    respond_to do |format|
      @article = Article.find(params[:article_id])
      @article.update_attribute :row_order_position, params[:index]
      format.json { render :json => { :status => "success" } }
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    flash[:notice] = "Article successfully deleted!"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(
      :title,
      :content,
      :major_section_id,
      :minor_section_id
    )
  end
end

app/controllers/major_sections_controller.rb
class MajorSectionsController < ApplicationController
  def new
    @major_section = MajorSection.new
  end

  def create
    @major_section = MajorSection.new(major_section_params)
    if @major_section.save
      flash[:notice] = "#{@major_section.name} successfully created!"
      redirect_to articles_path
    else
      flash.now[:alert] = @major_section.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @major_section = MajorSection.find(params[:id])
  end

  def update
    @major_section = MajorSection.find(params[:id])
    @major_section.assign_attributes(major_section_params)
    if @major_section.save
      flash[:notice] = "#{@major_section.name} successfully saved!"
      redirect_to articles_path
    else
      flash.now[:alert] = @major_section.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def drag_update
    respond_to do |format|
      @major_section = MajorSection.find(params[:major_section_id])
      @major_section.update_attribute :row_order_position, params[:index]
      format.json { render :json => { :status => "success" } }
    end
  end

  def destroy
    major_section = MajorSection.find(params[:id])
    flash[:notice] = "#{major_section.name} successfully deleted!"
    major_section.destroy
    redirect_to articles_path
  end

  private

  def major_section_params
    params.require(:major_section).permit(
      :name
    )
  end
end

app/controllers/minor_sections_controller.rb
class MinorSectionsController < ApplicationController
  def new
    @minor_section = MinorSection.new
  end

  def create
    @minor_section = MinorSection.new(minor_section_params)
    if @minor_section.save
      flash[:notice] = "#{@minor_section.name} successfully created!"
      redirect_to articles_path
    else
      flash.now[:alert] = @minor_section.errors.full_messages.to_sentence
      render "new"
    end
  end

  def edit
    @minor_section = MinorSection.find(params[:id])
  end

  def update
    @minor_section = MinorSection.find(params[:id])
    @minor_section.assign_attributes(minor_section_params)
    if @minor_section.save
      flash[:notice] = "#{@minor_section.name} successfully saved!"
      redirect_to articles_path
    else
      flash.now[:alert] = @minor_section.errors.full_messages.to_sentence
      render "edit"
    end
  end

  def drag_update
    respond_to do |format|
      @minor_section = MinorSection.find(params[:minor_section_id])
      @minor_section.update_attribute :row_order_position, params[:index]
      format.json { render :json => { :status => "success" } }
    end
  end

  def destroy
    minor_section = MinorSection.find(params[:id])
    flash[:notice] = "#{minor_section.name} successfully deleted!"
    minor_section.destroy
    redirect_to articles_path
  end

  private

  def minor_section_params
    params.require(:minor_section).permit(
      :name,
      :major_section_id
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article_list_item.html.slim
li.article-list-item data-url="#{article_drag_update_path(article.id)}"
  .list-group
    a.list-group-item href="#{article_path(article)}"
      h4.list-group-item-heading
        = article.title
      p.list-group-item-text
        = truncate(strip_tags(article.content), length: 100)
  .action-links 
    a href="#{edit_article_path(article)}"
      i.fa.fa-pencil-square-o
    = link_to "<i class='fa fa-trash-o'></i>".html_safe, { :id => article.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this article..." }

app/views/articles/_form.html.slim
.article-form-holder ng-controller="ArticlesFormCtrl" data-has-minor-section="#{@article.minor_section_id.present?}"
  = simple_form_for(@article) do |form|
    = form.input :title
    = form.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }

    label
      | Belongs to

    br

    div
      .btn-group data-toggle="buttons"
        label.btn.btn-primary ng-click="majorSectionClicked()" ng-class="{'active': showMajorSection}"
          input type="radio" name="section" id="majorSection" autocomplete="off" checked=""
            | Major section
        label.btn.btn-primary ng-click="minorSectionClicked()" ng-class="{'active': !showMajorSection}"
          input type="radio" name="section" id="minorSection" autocomplete="off"
            | Minor section

    br

    div ng-show="showMajorSection"
      = form.association :major_section, include_blank: "Select a major section to belong to"

    div ng-show="!showMajorSection"
      = form.association :minor_section, include_blank: "Select a major section to belong to"

    = form.submit class: 'btn btn-success'

app/views/articles/_major_section_list_item.html.slim
h1.page-header
  i.major-section-move-icon.fa.fa-arrows
  = major_section.name
  small.major-section-actions
    a href="#{edit_major_section_path(major_section)}"
      i.fa.fa-pencil-square-o
    = link_to "<i class='fa fa-trash-o'></i>".html_safe, { :id => major_section.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this major section and all the minor sections and articles associated with it..." }

app/views/articles/_minor_section_list_item.html.slim
h3.page-header
  i.minor-section-move-icon.fa.fa-arrows
  = minor_section.name
  small.major-section-actions
    a href="#{edit_minor_section_path(minor_section)}"
      i.fa.fa-pencil-square-o
    = link_to "<i class='fa fa-trash-o'></i>".html_safe, { :id => minor_section.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this minor section and all the articles associated with it..." }

app/views/articles/edit.html.slim
.row
  .col-xs-12
    h3
      | Edit article

    = render "form"

    br
    
    = link_to "Delete".html_safe, { :id => @article.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this article..." }

app/views/articles/index.html.slim
ul.major-sections-list ng-controller="MajorSectionsListCtrl"
  - @major_sections.each do |major_section|
    li data-url="#{major_section_drag_update_path(major_section.id)}"
      = render "major_section_list_item", major_section: major_section

      ul.article-list ng-controller="ArticlesListCtrl"
        - major_section.articles.ordered.each do |article|
          = render "article_list_item", article: article

      ul.minor-sections-list ng-controller="MinorSectionsListCtrl"
        - major_section.minor_sections.ordered.each do |minor_section|
          li data-url="#{minor_section_drag_update_path(minor_section.id)}"
            = render "minor_section_list_item", minor_section: minor_section

            ul.article-list ng-controller="ArticlesListCtrl"
              - minor_section.articles.ordered.each do |article|
                = render "article_list_item", article: article

app/views/articles/new.html.slim
= simple_form_for(@article, html: { class: 'form-horizontal' }) do |form|
  = form.input :title
  = form.input :content, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} }

app/views/articles/show.html.slim
ol.breadcrumb
  - if @article.minor_section
    li.active
      = "Major section: #{@article.minor_section.major_section.name}"
    li.active
      = "Minor section: #{@article.minor_section.name}"
  - elsif @article.major_section
    li.active
      = "Major section: #{@article.major_section.name}"

h1
  = @article.title

p
  = link_to "Edit", edit_article_path(@article)

div
  = @article.content.html_safe

app/views/layouts/_alerts.html.slim
- unless notice.blank?
  .alert.alert-success.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true"
        | &times;
    = notice.html_safe

- unless alert.blank?
  .alert.alert-danger.alert-dismissible role="alert"
    button type="button" class="close" data-dismiss="alert" aria-label="Close"
      span aria-hidden="true"
        | &times;
    = alert.html_safe

app/views/layouts/_nav.html.slim
= nav_bar brand: "Obstetrics", responsive: true do ||
  = menu_group do ||
    = menu_item "New Major Section", new_major_section_path
    = menu_item "New Minor Section", new_minor_section_path
    = menu_item "New Article", new_article_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" ng-app="obstetrics">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Obstetrics</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "layouts/nav" %>
    <%= render "layouts/alerts" %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/major_sections/_form.html.slim
= simple_form_for(@major_section) do |form|
  = form.input :name
  = form.submit class: 'btn btn-success'

app/views/major_sections/edit.html.slim
.row
  .col-xs-12
    h3
      | Edit major section

    = render "form"

    br
    
    = link_to "Delete".html_safe, { :id => @major_section.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this major section and all the minor sections and articles associated with it..." }

app/views/major_sections/new.html.slim
.row
  .col-xs-12
    h3
      | New major section

    = render "form"

app/views/minor_sections/_form.html.slim
= simple_form_for(@minor_section) do |form|
  = form.input :name
  = form.association :major_section, include_blank: "Select a major section to belong to"
  = form.submit class: 'btn btn-success'

app/views/minor_sections/edit.html.slim
.row
  .col-xs-12
    h3
      | Edit minor section

    = render "form"

    br
    
    = link_to "Delete".html_safe, { :id => @minor_section.id, :action => :destroy }, :method => :delete, data: { confirm: "Are you sure?  You're about to delete this minor section and all the articles associated with it..." }

app/views/minor_sections/new.html.slim
.row
  .col-xs-12
    h3
      | New minor section

    = render "form"